import time

def name_scene():
    print()
    print("___________________________________________________________")
    print("                                                           ")
    print("                                                           ")
    print("                                                           ")
    prompt = "당신의 이름을 입력하세요 : "
    for char in prompt:
        print(char, end='', flush=True)
        time.sleep(0.09)
        
    user_name=input("")
    print()
    print("                                                           ")
    print("                                                           ")
    print("                                                           ")
    print("___________________________________________________________")

    scene_2022(user_name)

def scene_2022(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2022년 3월 3일 뉴스")
    time.sleep(1)
    print("블라디미르 푸틴 대통령이 지난 2월 24일 11시 50분경 우크라이나 지역에 \'특별 군사 작전\'을 시행 했습니다.")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("키이우 북쪽에서 전략 거점에서 우크라이나군과 러시아군의 교전이 일어났고,")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("어제부로 러시아 군이 확실한 우위를 점하고 끝났습니다. 현재 키이우는 러시아군의 통제하에 있습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("세계 각국의 외교관들은 전세계에서의 확전을 두려워 하고 있습니다. ")
    time.sleep(1)
    print("")
    time.sleep(1)
    print(f"{user_name} : 과연 재미난 시대로군 ")
    time.sleep(1)
    print("_____________________________________________________________________________________")

    scene_2023(user_name)

def scene_2023(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2023년 12월 9일 뉴스")
    time.sleep(1)
    print("모스크바에서 우크라이나의 미래를 논의하기 위한 회담이 진행되었습니다.")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("우크라이나 지역을 러시아로 합병 시키기 위한 주민 투표가 시행되었습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("우크라이나 저항군들은 그들의 절망적인 상황에도 불구하고, 그들의 영토를 포기하길 거부하고 있습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("러시아 쇼이구 국방장관은, \"더이상 이들을 지구상에 남겨두지 않을것\"이라는 기자회견을 했습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print(f"{user_name} : 불쌍하지만 그들의 운명에 맡길수밖에.. ")
    time.sleep(1)
    print("_____________________________________________________________________________________")
    scene_2024_1(user_name)

def scene_2024_1(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2024년 6월 15일 뉴스")
    time.sleep(1)
    print("중국은 대만의 독립 선언에 분개하여 하늘아래 두 정부는 있을수 없다는 사실을 공표했습니다.")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("현재로써 중국은 대만섬을 중국의 분리된 나머지 영역으로 보고 있습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("이제 중국은 대만섬이 24시간 내에 독립 선언을 철회하고 주권을 양도할것을 요구하고 있으며,")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("이를 따르지 않을 경우 힘든 대가를 치르게 할것 이라고 했습니다.")
    print("")
    time.sleep(1)
    print("미국 외교부 대변인은.\"세계 민주주의와 자유를 보존하는 것은 우리의 역할\"")
    print("")
    time.sleep(1)
    print("이라며 강한 대만 수호 의지를 나타냈습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print(f"{user_name} : 이것으로 더이상 전쟁은 없었으면 좋겠군. ")
    time.sleep(1)
    print("_____________________________________________________________________________________")
    scene_2024_2(user_name)

def scene_2024_2(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2024년 6월 16일 뉴스")
    time.sleep(1)
    print("중국은 전쟁 준비로 진먼섬 인근에 군대를 배치했습니다.")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("대만 위기를 평화적으로 협상해 끝내고자 베이징에서 중국, 미국, 대만간의 회담이 열렸습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("긴 회담 끝에 회담은 결렬되었습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("중국-대만 해상국경에 중국 함대가 자리를 잡았고, 인근 해역을 지나는 모든 상선은 항로를 변경했습니다.")
    print("")
    time.sleep(1)
    print("\"사령관님! 대통령실에서 해외 파병을 준비하라는 지시입니다!\"")
    print("")
    time.sleep(1)
    print("\"해병대 1사단, 육군 수기사단, 저희 1함대가 파병부대로 선정되었습니다!\"")
    time.sleep(1)
    print("")
    time.sleep(1)
    print(f"{user_name} : 우린 자유의 편에 설것이다. ")
    time.sleep(1)
    print("_____________________________________________________________________________________")
    scene_2024_3(user_name)

def scene_2024_3(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2024년 6월 30일")
    time.sleep(1)
    print("ROKN 독도함에서 사령부에게 전달! 우린 공격을 받고있다!")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("어제부터 본함을 추적하고 있던 미확인 잠수함의 공격으로 보이는 어뢰에 피격된것으로 보인다!")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("중국 해군 함정들이 본 함으로 항주해오고 있다! 기관부가 피격당해서 전투를 회피할수 없다!")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("제발 저들을 어떻게든지 못오게 해주십시오!........제발!")
    print("")
    time.sleep(1)
    print("(무선 잡음).................(폭발음이 들린다.))")
    print("")
    time.sleep(1)
    print("해병대 사령관 오정훈 중장입니다!")
    time.sleep(1)
    print("")
    time.sleep(1)
    print(f"{user_name} : 우선 당면한 전투를 치르게. 아주 어려운 싸움이 될거야. ")
    time.sleep(1)
    print("_____________________________________________________________________________________")
    scene_2024_4(user_name)
def scene_2024_4(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2024년 7월 2일")
    time.sleep(1)
    print("전투 보고 드리겠습니다.... 파병부대 22척중 5척 침몰, 7척 중파, 2척 반파.... 본함도 반파 상태입니다..")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("오정훈 중장 : 지금 대통령실은 난리가 났습니다.. 본국으로 퇴각하라는 지시입니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print(f"{user_name} : 우리에게 선전포고도 없이 왜 공격한것이지? ")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("오정훈 중장 : 저희만 그런것이 아닙니다. 미국 함대와 자위대도 박살이 났습니다.")
    print("")
    time.sleep(1)
    print("너무 많은 인명이 아무것도 아닌일에 희생됐다는 여론이 형성되며 엄청난수의 시위대가 광화문을 뒤덮었다.")
    print("")
    time.sleep(1)
    print("시위대는 더이상 해외 상황에 개입하지 않을 것을 요구하고 있습니다.")
    time.sleep(1)
    print("")
    print("_____________________________________________________________________________________")
    

name_scene()