import time

def name_scene():
    print()
    print("___________________________________________________________")
    print("                                                           ")
    print("                                                           ")
    print("                                                           ")
    prompt = "당신의 이름을 입력하세요"
    for char in prompt:
        print(char, end='', flush=True)
        time.sleep(0.09)
        
    user_name=input("")
    print()
    print("                                                           ")
    print("                                                           ")
    print("                                                           ")
    print("___________________________________________________________")

    scene_2022(user_name)

def scene_2022(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2022년 3월 3일뉴스")
    time.sleep(1)
    print("블라디미르 푸틴 대통령이 지난 2월 24일 11시 50분경 우크라이나 지역에 \'특별 군사 작전\'을 시행 했습니다.")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("키이우 북쪽에서 전략 거점에서 우크라이나군과 러시아군의 교전이 일어났고,")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("어제부로 러시아 군이 확실한 우위를 점하고 끝났습니다. 현재 키이우는 러시아군의 통제하에 있습니다.")
    time.sleep(1)
    print("")
    time.sleep(1)
    print("세계 각국의 외교관들은 전세계에서의 확전을 두려워 하고 있습니다. ")
    time.sleep(1)
    print("")
    time.sleep(1)
    print(f"{user_name} : 과연 재미난 시대로군 ")
    time.sleep(1)
    print("_____________________________________________________________________________________")

    scene_2023(user_name)

def scene_2023(user_name):
    print("_____________________________________________________________________________________")
    print("")
    print("")
    print("")
    print("2023년 12월 3일뉴스")
    time.sleep(1)
    print("모스크바에서 우크라이나의 미래를 논의하기 위한 회담이 진행되었습니다.")
    time.sleep(1)
    print("")                                    
    time.sleep(1)
    print("우크라이나 지역을 러시아로 합병 시키기 위한 주민 투표가 시행되었습니다.")
    time.sleep(1)
    print("                                                           ")
    time.sleep(1)
    print("우크라이나 저항군들은 그들의 절망적인 상황에도 불구하고, 그들의 영토를 포기하길 거부하고 있습니다.")
    time.sleep(1)
    print("                                                           ")
    time.sleep(1)
    print("러시아 쇼이구 국방장관은, \"더이상 이들을 지구상에 남겨두지 않을것\"이라는 기자회견을 했습니다.")
    time.sleep(1)
    print("                                                           ")
    time.sleep(1)
    print(f"{user_name} : 이것으로 더이상 전쟁은 없는걸까? ")
    time.sleep(1)
    print("_____________________________________________________________________________________")

name_scene()
